services:
  - type: web
    name: youtube-telegram-bot
    env: python
    buildCommand: |
      # Installation des dépendances système
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    healthCheckPath: /
    plan: free
    autoDeploy: true